const CountryData = [
  { id: 1, name: "Việt Nam", code: "VN", description: "Quốc gia Đông Nam Á" },
  { id: 2, name: "Hoa Kỳ", code: "US", description: "Quốc gia Bắc Mỹ" },
  { id: 3, name: "Nhật Bản", code: "JP", description: "Quốc gia Đông Á" },
  { id: 4, name: "Hàn Quốc", code: "KR", description: "Quốc gia Đông Á" },
  { id: 5, name: "Trung Quốc", code: "CN", description: "Quốc gia Đông Á" },
  { id: 6, name: "Thái Lan", code: "TH", description: "Quốc gia Đông Nam Á" },
  { id: 7, name: "Singapore", code: "SG", description: "Quốc gia Đông Nam Á" },
  { id: 8, name: "Lào", code: "LA", description: "Quốc gia Đông Nam Á" },
  { id: 9, name: "Campuchia", code: "KH", description: "Quốc gia Đông Nam Á" },
  { id: 10, name: "Myanmar", code: "MM", description: "Quốc gia Đông Nam Á" },
  { id: 11, name: "Indonesia", code: "ID", description: "Quốc gia Đông Nam Á" },
  { id: 12, name: "Malaysia", code: "MY", description: "Quốc gia Đông Nam Á" },
  { id: 13, name: "Philippines", code: "PH", description: "Quốc gia Đông Nam Á" },
  { id: 14, name: "Ấn Độ", code: "IN", description: "Quốc gia Nam Á" },
  { id: 15, name: "Anh", code: "GB", description: "Quốc gia Châu Âu" },
  { id: 16, name: "Pháp", code: "FR", description: "Quốc gia Châu Âu" },
  { id: 17, name: "Đức", code: "DE", description: "Quốc gia Châu Âu" },
  { id: 18, name: "Ý", code: "IT", description: "Quốc gia Châu Âu" },
  { id: 19, name: "Tây Ban Nha", code: "ES", description: "Quốc gia Châu Âu" },
  { id: 20, name: "Nga", code: "RU", description: "Quốc gia Châu Âu/Châu Á" },
  { id: 21, name: "Canada", code: "CA", description: "Quốc gia Bắc Mỹ" },
  { id: 22, name: "Úc", code: "AU", description: "Quốc gia Châu Đại Dương" },
  { id: 23, name: "New Zealand", code: "NZ", description: "Quốc gia Châu Đại Dương" },
  { id: 24, name: "Brazil", code: "BR", description: "Quốc gia Nam Mỹ" },
  { id: 25, name: "Mexico", code: "MX", description: "Quốc gia Bắc Mỹ" },
];

export default CountryData;
